### ISSUE TITLE
Client charms cannot connect cross-controller

### ISSUE THREAD

**Issue by sinclert-canonical** [canonical/glauth-k8s-operator#120]
This issue describes a connection error, where, once an **LXD charm** tries to access LDAP relation data from the **Kubernetes** GLAuth charm (only version of the charm there is), the LDAP charm lib crashes when trying to read the password secret. The crash happens when calling the `consume_ldap_relation_data` [method](https://github.com/canonical/glauth-k8s-operator/blob/594a7bc57c09b50f44cbd183c712b31a45a22d5f/lib/charms/glauth_k8s/v0/ldap.py#L502-L519), when fetching the secret using `bind_password_secret` as secret ID (see [code](https://github.com/canonical/glauth-k8s-operator/blob/594a7bc57c09b50f44cbd183c712b31a45a22d5f/lib/charms/glauth_k8s/v0/ldap.py#L517)).

<details>
  <summary>See crash traceback</summary>
  <img width="1182" alt="Image" src="https://github.com/user-attachments/assets/60766d48-8389-4725-b2ae-91da45d24a8c" />
</details>

---

### How to reproduce:
1. **[K8s]** Deploy GLAuth charm following [this tutorial](https://charmhub.io/glauth-k8s/docs/tutorial):
    ```shell
    # Create model
    juju add-model glauth
    
    # Deploy GLAuth
    juju deploy postgresql-k8s --channel 14/stable --trust
    juju deploy self-signed-certificates
    juju deploy glauth-k8s --channel edge --trust
    
    # Relate everything together
    juju integrate glauth-k8s postgresql-k8s
    juju integrate glauth-k8s self-signed-certificates
    juju integrate glauth-k8s glauth-utils
    ```

2. **[K8s]** Enable microk8s metallb:
    ```shell
    IPADDR=$(ip -4 -j route get 2.2.2.2 | jq -r '.[] | .prefsrc')
    sudo microk8s enable metallb:$IPADDR-$IPADDR
    ```

3. **[K8s]** Deploy Traefik charm:
    ```shell
    juju deploy traefik-k8s --trust
    juju integrate traefik-k8s glauth-k8s:ingress
    ```

4. **[K8s]** Expose cross-model relationships
    ```shell
    juju offer glauth-k8s:ldap ldap
    juju offer glauth-k8s:send-ca-cert send-ca-cert
    ```

5. **[LXD]** Switch to an LXD controller
    ```shell
    juju switch <lxd_controller>
    juju add-model postgresql
    ```

6. **[LXD]** Deploy LDAP integration containing client charm:
    ```shell
    # Build a local copy of the PostgreSQL charm
    git clone https://github.com/canonical/postgresql-operator && cd postgresql-operator
    git checkout sinclert/ldap-integration
    charmcraft pack
    
    # Deploy the locally built charm
    juju deploy ./postgresql_ubuntu@22.04-amd64.charm postgresql
    ```

7. **[LXD]** Relate K8s GLAuth charm and LXD client charm:
    ```shell
    # Consume cross-model relationships
    juju consume <k8s_controller>:admin/glauth.ldap
    juju consume <k8s_controller>:admin/glauth.send-ca-cert
    
    # Integrate charms together
    juju integrate postgresql:ldap ldap
    juju integrate postgresql:receive-ca-cert send-ca-cert
    ```

---

### Versions
- OS: Ubuntu 22.04.
- Arch: `amd64`.
- Juju: `3.6.2`.
- Microk8s: `1.32.2` (latest).
- GLAuth charm: `52` (latest).

**Comment by marceloneppel** [comment]
It seems to be the same error from https://bugs.launchpad.net/juju/+bug/2046484. Maybe it's not fixed for a cross-model relation between different substrates (like LXD + K8s, in this case).

**Comment by nsklikas** [comment]
AFAIK there was an issue with sharing secrets that was fixed in juju 3.6.4. I haven't not performed this test, but the integration works for sssd, this means that probably there is some configuration missing from your setup. 
If I understand correctly, you need to register the k8s secret backend with the machine juju controller (see [here](https://github.com/juju/juju/pull/18599) for some instructions).

Can you retry with a newer version of juju while registering the backend? Also maybe @NucciTheBoss has some info on this, as he did the sssd integration.

**Comment by sinclert-canonical** [comment]
> It seems to be the same error from https://bugs.launchpad.net/juju/+bug/2046484

Yes, it is the same problem! According to the bug report it got fixed in Juju 3.3.3, but I am still seeing it...

**Comment by sinclert-canonical** [comment]
> AFAIK there was an issue with sharing secrets that was fixed in juju 3.6.4.

I just un-installed juju `3.6.2`, and installed + configured juju `3.6.4`. I am still encountering the problem.

> If I understand correctly, you need to register the k8s secret backend with the machine juju controller

That is a promising reference. After checking the [this piece of documentation](https://documentation.ubuntu.com/juju/latest/user/reference/juju-cli/list-of-juju-cli-commands/add-secret-backend/), it seems like there is a way to add secret-backends to a different model. Hopefully adding the GLAuth k8s secret backend to the PostgreSQL LXD model would solve the problem. However, such command requires a config file to be provided, which I am not sure how it must look like 😕 

@NucciTheBoss could you guide us here?

**Comment by NucciTheBoss** [comment]
@sinclert-canonical the issue is the address your Postgres machine is using to contact the Kubernetes API. If you look in your crashdump logs, you'll see that your Postgres machine is attempting to use the localhost address `127.0.0.1` to reach the Kubernetes API which won't work because `microk8s` is not running inside your Postgres LXD machine, but Juju thinks it is.

This isn't a problem with glauth-k8s, but rather microk8s and `kubectl` because they tell Juju that the Kubernetes API endpoint is 127.0.0.1 rather than the public address of your local machine. If you run `juju show-cloud microk8s`, you'll more than likely see that Juju has the endpoint of your microk8s cloud configured to be 127.0.0.1.

To get around this issue, you have two options:

1. Update you microk8s cloud configuration in Juju to have the endpoint be the public IP address of your computer (`hostname -I`) and then retry the cross-model integration between Postgres and glauth-k8s.
2. Use Canonical K8s (`sudo snap install k8s --classic`) rather than microk8s. `sudo k8s config` will use your computer's public IP address as the Kubernetes API endpoint rather than `127.0.0.1`.

Update the endpoint configuration for your k8s cloud in Juju and your Postgres machine will be able to access the bind password secret.

**Comment by NucciTheBoss** [comment]
That's not what `metallb` does; it doesn't modify your Kubernetes API endpoint. `metallb` enables a [LoadBalancer](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/) that provides externally accessible IP addresses to your Kubernetes cluster nodes, and routes traffic from external applications to those nodes.

So `metallb` provides the IP address used by `traefik-k8s` to make applications like Grafana and GLAuth accessible to applications outside of the Kubernetes cluster like SSSD or HPC workload schedulers.

What you need to change is your microk8s cloud configuration in Juju to use public address of the machine you're running LXD and microk8s on:

```shell
export IPADDR=$(ip -4 -j route get 2.2.2.2 | jq -r '.[] | .prefsrc')
kubectl config view --raw | yq '.clusters[].cluster.server = "https://\(strenv(IPADDR)):6643"' | juju add-k8s k8s-cloud
```

You could possibly use the `juju update-k8s` command to update the configuration of your microk8s cloud, but IIRC it uses the _clouds.yaml_ YAML schema rather than the _kubeconfig_ YAML schema.

**Comment by nsklikas** [comment]
Thank you very much @NucciTheBoss for the quick help (TIL). @sinclert-canonical can we close this?

**Comment by sinclert-canonical** [comment]
> @sinclert-canonical can we close this?

Happy to do so if this is unequivocally identified as a non GLAuth specific bug. However, it is clear to me that this conversation needs to continue somewhere. Any suggestions?

**Comment by shipperizer** [comment]
@sinclert-canonical if you spin up any unit inside via the lxd controller adn try to curl the address

`127.0.0.1:16443/api/v1/namespaces/glauth` what do you get?

if it's always a connection refused it is unequivocally a non-charm related issue

mind troubleshooting with that?

> Is there any place where cross-controller relationships are documented and explained?

regarding this point, I am not aware that this is a charm domain, we don't distinguish between cross controller vs standard (same controller), databag is the same so we wouldn't be able to do anything about it

there is cross-model documentation https://documentation.ubuntu.com/juju/latest/user/reference/relation/ but not cross-controller

**Comment by sinclert-canonical** [comment]
> If you spin up any unit inside via the lxd controller adn try to curl the address `127.0.0.1:16443/api/v1/namespaces/glauth` what do you get?

I get a connection refused error:

<details>
    <summary>See curl command</summary>
    <img width="680" alt="Image" src="https://github.com/user-attachments/assets/206d8610-8e65-4a50-8ab4-b68827c98eda" />
</details>

---

> regarding this point, I am not aware that this is a charm domain, we don't distinguish between cross controller vs standard (same controller), databag is the same so we wouldn't be able to do anything about it

Oh, ok. Well, then it is not a charm developer issue, but a.... Juju? microk8s? issue 🤷‍♂ 

I am happy to close the issue, as this is not GLAuth specific, but please, **help me find a place to continue the conversation**, because this is affecting a few of us in Data Platform, and we are unsure how to proceed / who to ping.

**Comment by sinclert-canonical** [comment]
> If you spin up any unit inside via the lxd controller and try to curl the address `127.0.0.1:16443/api/v1/namespaces/glauth` what do you get?

I get a connection refused error:

<details>
    <summary>See curl command</summary>
    <img width="680" alt="Image" src="https://github.com/user-attachments/assets/206d8610-8e65-4a50-8ab4-b68827c98eda" />
</details>

---

> Regarding this point, I am not aware that this is a charm domain, we don't distinguish between cross controller vs standard (same controller), databag is the same so we wouldn't be able to do anything about it

Oh, ok. Well, then it is not a charm developer issue, but a.... Juju? microk8s? issue 🤷‍♂ 

I am happy to close the issue, as this is not GLAuth specific, but please, **help me find a place to continue the conversation**, because this is affecting a few of us in Data Platform, and we are unsure how to proceed / who to ping.

**Comment by NucciTheBoss** [comment]
We could start a thread in the Charmed HPC project discussion board: https://github.com/orgs/charmed-hpc/discussions 

We're likely going to add some explanation and reference documentation to outline the hybrid architecture that we use for Charmed HPC where we have a k8s control/auxiliary plane and a machine plane for the compute nodes. I haven't had issues retrieving secrets, but I'm also using Canonical K8s rather than microk8s so that may be a factor.

@sinclert-canonical in that discussions thread, could you show what the output of `juju show-cloud microk8s` is?

**Comment by sinclert-canonical** [comment]
> We could start a thread in the Charmed HPC project discussion board: https://github.com/orgs/charmed-hpc/discussions

Thanks Jason, I will make sure to open a new discussion there, as soon as I have a chance to talk to the other engineers working with the GLAuth within Data Platform. I want to double check that they cannot make cross-controller relations work, just as I can't, before moving this topic somewhere else.

Please, keep the issue open until Monday.

**Comment by sinclert-canonical** [comment]
🗞 Some news before I close this issue:

- I repeated the whole experiment using a cross-cloud controller, with `microk8s` 1.29, instead of 1.32 (latest), following the steps from the Juju _Set Thing up_ [documentation](https://documentation.ubuntu.com/juju/latest/user/howto/manage-your-deployment/manage-your-deployment-environment/#set-things-up). The connection errors kept happening.
- I repeated the whole experiment using a shared-cloud controller, and the integration worked as expected, so I renamed the issue to focus on the cross-controller situation, and not in the cross-model one.

I still do not know what is wrong with me setup, but I believe it may be independent to GLAuth. Therefore, I will open the issue here, and move the conversation to the Charmed HPC [discussions page](https://github.com/orgs/charmed-hpc/discussions).

**Comment by sinclert-canonical** [comment]
**TLDR: The built-in microk8s cloud cannot be used to test cross-controller relations**

For anyone else arriving to this issue:

The problem with the setup I was using (the one officially recommented by [Juju docs](https://documentation.ubuntu.com/juju/latest/howto/manage-your-deployment/manage-your-deployment-environment/)), is that it relied on the **built-in** microk8s cloud that gets installed by default, once the `microk8s` snap gets installed into the system. This type of cloud cannot be updated via `juju update-k8s` command, so its IP will continue to be `127.0.0.1`.

The solution is to define a "new cloud" by leveraging the `juju add-k8s` command, in order to create one of type **local**, so that its main endpoint could be tweaked to be whatever the Juju cluster administrator wants (i.e. the computer public IP).

```shell
# Export microk8s config
microk8s.kubectl config view --raw > ~/.kube/config

# Replace localhost IP by the computer public IP
export LOCAL_IP="127.0.0.1"
export PUBLIC_IP=$(ip -4 -j route get 2.2.2.2 | jq -r '.[] | .prefsrc')
sed -i 's/'${LOCAL_IP}'/'${PUBLIC_IP}'/g' ~/.kube/config

# Create new cloud using modified config
cat ~/.kube/config | juju add-k8s microk8s-cluster --cluster-name=microk8s-cluster

# Bootstrap the microk8s controller
juju bootstrap microk8s k8s-controller
```

<details>
  <summary>When running juju  clouds</summary>

  ![Image](https://github.com/user-attachments/assets/7fe8ef44-46d6-46a4-892a-ecef0391882d)
</details>
